baseURL: https://www.maxence-lagalle.fr

languageCode: fr-fr
title: "Maxence Lagalle"
theme:
  - "github.com/hugo-toha/toha/v4"
  - "github.com/dzello/reveal-hugo"

# Use Hugo modules to add theme
module:
  imports:
    - path: github.com/hugo-toha/toha/v4
    - path: github.com/dzello/reveal-hugo
  mounts:
    - source: static
      target: static
    - source: static/files
      target: static/files
    - source: ./node_modules/flag-icon-css/flags
      target: static/flags
    - source: ./node_modules/@fontsource/mulish/files
      target: static/files
    - source: ./node_modules/katex/dist/fonts
      target: static/fonts

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  fr:
    languageName: Francais
    weight: 1

# Force a locale to be use, really useful to develop the application ! Should be commented in production, the "weight" should rocks.
DefaultContentLanguage: fr

# Allow raw html in markdown file
markup:
  # this disables hugo's syntax highlighting.
  codeFences: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Background image of the landing page
  background: /images/site/background.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    main: /images/author/ml.jpg
    inverted: /images/author/ml.jpg
    favicon: /images/author/ml.jpg

  # GitHub repo of your site
  gitRepo: https://github.com/maxence-lagalle/maxence-lagalle.github.io
  # Default branch of your Git repo
  gitBranch: main

  # Configure the number of section title visible in the top navbar
  topNavbar:
    maxVisibleSections: 6

  # Configure various features of this theme
  features:
    # Enable dark theme
    darkMode:
      enable: true
      services:
        darkreader:
          defaultColorScheme: system # options are 'system', 'dark', 'light'
          fixes:
            invert: [ 'img[src$=".svg"]' ] # inverts svg colors.
          theme:
            brightness: 100
            contrast: 100
            sepia: 0

    # Enable and configure portfolio
    portfolio:
      enable: true

    # Enable and configure blog posts
    blog:
      enable: false
      # Share post on different social media
      shareButtons:
        facebook: false
        twitter: false
        linkedin: false
        reddit: false
        whatsapp: false
        email: true
        # tumblr: true
        # pocket: true
        # diaspora: true
        # mastodon: true

    # Enable & configure "Notes" features
    notes:
      enable: false

    # Enable comment feature. There, should be only one of them.
    comment:
      enable: false

    # Enable Analytics
    analytics:
      enabled: false

    # Enable Support
    support:
      enable: false

    # specify whether you want to show Table of Contents in reading page
    toc:
      enable: true

    # Show tags under the post title
    tags:
      enable: true

    # Specify whether to show flag in the language selector. Default is true.
    flags:
      enable: false

    # Enable this to use `embed-pdf` shortcode.
    embedpdf:
      enable: false

    # Enable this to create flowcharts using shortcodes.
    flowchart:
      enable: true
      services:
        # Uncomment for `mermaid` shortcode.
        mermaid:
        # For config options, see: https://mermaid-js.github.io/mermaid/#/Setup?id=configuration
          theme: dark

    # Enable this to create mathematic expressions using `$$` blocks
    math:
      enable: true
      services:
        # https://katex.org/docs/autorender.html#api for more configurations
        katex:
          delimiters:
            - left: $$
              right: $$
              display: true
            - left: \\[
              right: \\]
              display: true
            - left: $
              right: $
              display: false
            - left: \\(
              right: \\)
              display: false

    # Enable to use custom syntax highlight
    # Please note, Hugo comes with it's own html based syntax highlighter.
    # Your code block will still be syntax highlighted by hugo.
    # For more details: https://gohugo.io/content-management/syntax-highlighting/
    # To disable Hugo's builtin syntax highlight,
    # see: https://gohugo.io/getting-started/configuration-markup#highlight
    syntaxHighlight:
      enable: true
      services:
        hljs:
          # see: https://highlightjs.readthedocs.io/en/latest/api.html#configure
          noHighlightRe: /^no-highlight$/i

    # Enable to use `video-player` shortcode
    videoPlayer:
      enable: true
      services:
        # convert .js-player class into video player via https://plyr.io/
        # Can play HTML5 Video, Audio, Youtube, Vimeo.
        # For more info on setup: https://github.com/sampotts/plyr#quick-setup
        plyr:
        # options doc: https://github.com/sampotts/plyr#options
          enabled: true

  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    # template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
      # show custom menus in the footer
      customMenus: true
      # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true
    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".
    newsletter:
      enable: false
    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: false